name: build

on:
  push:
    branches:
      - master
    tags:
      - v*

  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.9

      - name: Install NDK
        run: sdkmanager --install "ndk;$(grep ndkVersion app/gradle.properties | cut -d= -f2)"

      - name: Build
        run: ./gradlew build

      - name: Copy and rename binary
        if: matrix.os == 'ubuntu-18.04' && startsWith(github.ref, 'refs/tags/')
        run: cp app/build/outputs/apk/debug/app-debug.apk roc-droid.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'ubuntu-18.04' && startsWith(github.ref, 'refs/tags/')
        with:
          files: roc-droid.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull request artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
         commit: ${{ github.event.pull_request.head.sha }}
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         artifacts-token: ${{ secrets.ANOTHER_TOKEN_WITH_PUSH_ACCESS }}
         artifacts-repo: some/repo
         artifacts: |
               roc-droid.apk
                  
